namespace Relational.BaseModels.AspNetCore.Generics.Annotations
{
    public class FieldModel : EntityModel
    {
        public FieldModel(int row,int order, int width, string id, bool isKey, string displayName, bool autogenerated, ControlType controlType, string tabId, string entityId) : base(order, width, id, isKey, displayName, entityId)
        {
            Row = row;
            Autogenerated = autogenerated;
            ControlType = controlType;
            TabId = tabId;
        }
        public int Row { get; set; }
        public bool Autogenerated { get; }
        public string TabId { get; }
        public ControlType ControlType { get; }
        public ListModel List { get; set; }
    }
}
