using System.Runtime.CompilerServices;

namespace Relational.BaseModels.AspNetCore.Generics.Annotations
{
    public class FieldAttribute: EntityAttribute
    {
        public FieldAttribute(int order, int row, [CallerMemberName] string id = "", string displayName = "", bool isKey = false, int width = 6, bool autogenerated = false, ControlType controlType = ControlType.Text, string tabId="") : base(id, displayName, order, isKey, width)
        {
            Row = row;
            ControlType = controlType;
            Autogenerated = autogenerated;
            TabId = tabId;
        }
        public int Row { get; }
        public bool Autogenerated { get; }
        public string TabId { get; }
        public ControlType ControlType { get; }

    }
}
